[2025-03-03T14:25:20.072+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 4_4_house_assignment.upload_to_clickhouse scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2025-03-03T14:25:20.077+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 4_4_house_assignment.upload_to_clickhouse scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2025-03-03T14:25:20.077+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-03-03T14:25:20.087+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): upload_to_clickhouse> on 2024-01-05 00:00:00+00:00
[2025-03-03T14:25:20.092+0000] {standard_task_runner.py:60} INFO - Started process 2344 to run task
[2025-03-03T14:25:20.094+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', '4_4_house_assignment', 'upload_to_clickhouse', 'scheduled__2024-01-05T00:00:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/4_4_house_assignment.py', '--cfg-path', '/tmp/tmpnl3ux0dz']
[2025-03-03T14:25:20.096+0000] {standard_task_runner.py:88} INFO - Job 18: Subtask upload_to_clickhouse
[2025-03-03T14:25:20.123+0000] {task_command.py:423} INFO - Running <TaskInstance: 4_4_house_assignment.upload_to_clickhouse scheduled__2024-01-05T00:00:00+00:00 [running]> on host 9a2e4036dec3
[2025-03-03T14:25:20.160+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='4_4_house_assignment' AIRFLOW_CTX_TASK_ID='upload_to_clickhouse' AIRFLOW_CTX_EXECUTION_DATE='2024-01-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-05T00:00:00+00:00'
[2025-03-03T14:25:20.166+0000] {connection.py:411} WARNING - Failed to connect to localhost:9000
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/clickhouse_driver/connection.py", line 399, in connect
    return self._init_connection(host, port)
  File "/home/airflow/.local/lib/python3.9/site-packages/clickhouse_driver/connection.py", line 329, in _init_connection
    self.socket = self._create_socket(host, port)
  File "/home/airflow/.local/lib/python3.9/site-packages/clickhouse_driver/connection.py", line 301, in _create_socket
    raise err
  File "/home/airflow/.local/lib/python3.9/site-packages/clickhouse_driver/connection.py", line 292, in _create_socket
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
[2025-03-03T14:25:20.166+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/4_4_house_assignment.py", line 74, in upload_to_clickhouse
    client.execute(f'CREATE TABLE IF NOT EXISTS {table_name} (num_code Int64, char_code String, nominal Int64, name String, value String, date String) ENGINE Log')
  File "/home/airflow/.local/lib/python3.9/site-packages/clickhouse_driver/client.py", line 370, in execute
    with self.disconnect_on_error(query, settings):
  File "/usr/local/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/home/airflow/.local/lib/python3.9/site-packages/clickhouse_driver/client.py", line 313, in disconnect_on_error
    self.establish_connection(settings)
  File "/home/airflow/.local/lib/python3.9/site-packages/clickhouse_driver/client.py", line 300, in establish_connection
    self.connection.force_connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/clickhouse_driver/connection.py", line 258, in force_connect
    self.connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/clickhouse_driver/connection.py", line 420, in connect
    raise err
clickhouse_driver.errors.NetworkError: Code: 210. Connection refused (localhost:9000)
[2025-03-03T14:25:20.172+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=4_4_house_assignment, task_id=upload_to_clickhouse, execution_date=20240105T000000, start_date=20250303T142520, end_date=20250303T142520
[2025-03-03T14:25:20.180+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 18 for task upload_to_clickhouse (Code: 210. Connection refused (localhost:9000); 2344)
[2025-03-03T14:25:20.227+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-03-03T14:25:20.236+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-03T14:28:11.985+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 4_4_house_assignment.upload_to_clickhouse scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2025-03-03T14:28:11.991+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 4_4_house_assignment.upload_to_clickhouse scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2025-03-03T14:28:11.991+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-03-03T14:28:12.004+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): upload_to_clickhouse> on 2024-01-05 00:00:00+00:00
[2025-03-03T14:28:12.009+0000] {standard_task_runner.py:60} INFO - Started process 2650 to run task
[2025-03-03T14:28:12.012+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', '4_4_house_assignment', 'upload_to_clickhouse', 'scheduled__2024-01-05T00:00:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/4_4_house_assignment.py', '--cfg-path', '/tmp/tmp_f1ll2b8']
[2025-03-03T14:28:12.013+0000] {standard_task_runner.py:88} INFO - Job 18: Subtask upload_to_clickhouse
[2025-03-03T14:28:12.041+0000] {task_command.py:423} INFO - Running <TaskInstance: 4_4_house_assignment.upload_to_clickhouse scheduled__2024-01-05T00:00:00+00:00 [running]> on host 9a2e4036dec3
[2025-03-03T14:28:12.099+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='4_4_house_assignment' AIRFLOW_CTX_TASK_ID='upload_to_clickhouse' AIRFLOW_CTX_EXECUTION_DATE='2024-01-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-05T00:00:00+00:00'
[2025-03-03T14:28:12.236+0000] {unix.py:142} WARNING - /etc/timezone is deprecated on Debian, and no longer reliable. Ignoring.
[2025-03-03T14:28:12.243+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-03-03T14:28:12.247+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=4_4_house_assignment, task_id=upload_to_clickhouse, execution_date=20240105T000000, start_date=20250303T142811, end_date=20250303T142812
[2025-03-03T14:28:12.265+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-03T14:28:12.274+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-10T09:49:11.109+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 4_4_house_assignment.upload_to_clickhouse scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2025-03-10T09:49:11.116+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 4_4_house_assignment.upload_to_clickhouse scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2025-03-10T09:49:11.117+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-03-10T09:49:11.132+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): upload_to_clickhouse> on 2024-01-05 00:00:00+00:00
[2025-03-10T09:49:11.140+0000] {standard_task_runner.py:60} INFO - Started process 452 to run task
[2025-03-10T09:49:11.145+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', '4_4_house_assignment', 'upload_to_clickhouse', 'scheduled__2024-01-05T00:00:00+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/4_4_house_assignment.py', '--cfg-path', '/tmp/tmpcw397kyu']
[2025-03-10T09:49:11.148+0000] {standard_task_runner.py:88} INFO - Job 34: Subtask upload_to_clickhouse
[2025-03-10T09:49:11.197+0000] {task_command.py:423} INFO - Running <TaskInstance: 4_4_house_assignment.upload_to_clickhouse scheduled__2024-01-05T00:00:00+00:00 [running]> on host 9a2e4036dec3
[2025-03-10T09:49:11.271+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='4_4_house_assignment' AIRFLOW_CTX_TASK_ID='upload_to_clickhouse' AIRFLOW_CTX_EXECUTION_DATE='2024-01-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-05T00:00:00+00:00'
[2025-03-10T09:49:11.292+0000] {unix.py:142} WARNING - /etc/timezone is deprecated on Debian, and no longer reliable. Ignoring.
[2025-03-10T09:49:11.297+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-03-10T09:49:11.303+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=4_4_house_assignment, task_id=upload_to_clickhouse, execution_date=20240105T000000, start_date=20250310T094911, end_date=20250310T094911
[2025-03-10T09:49:11.359+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-10T09:49:11.370+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
