[2025-03-11T09:19:47.849+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: clickhouse_operator_example.create_table scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-03-11T09:19:47.860+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: clickhouse_operator_example.create_table scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-03-11T09:19:47.861+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-03-11T09:19:47.876+0000] {taskinstance.py:2191} INFO - Executing <Task(ClickHouseOperator): create_table> on 2024-01-01 00:00:00+00:00
[2025-03-11T09:19:47.883+0000] {standard_task_runner.py:60} INFO - Started process 481 to run task
[2025-03-11T09:19:47.885+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'clickhouse_operator_example', 'create_table', 'scheduled__2024-01-01T00:00:00+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/5_2_operator.py', '--cfg-path', '/tmp/tmpwjgj72at']
[2025-03-11T09:19:47.887+0000] {standard_task_runner.py:88} INFO - Job 50: Subtask create_table
[2025-03-11T09:19:47.924+0000] {task_command.py:423} INFO - Running <TaskInstance: clickhouse_operator_example.create_table scheduled__2024-01-01T00:00:00+00:00 [running]> on host 9a2e4036dec3
[2025-03-11T09:19:48.159+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='clickhouse_operator_example' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T00:00:00+00:00'
[2025-03-11T09:19:48.164+0000] {base.py:83} INFO - Using connection ID 'clickhouse_default' for task execution.
[2025-03-11T09:19:48.164+0000] {clickhouse.py:79} INFO - CREATE TABLE IF NOT EXISTS currency_sql (source String, currency String, value Float, date String) ENGINE Log
[2025-03-11T09:19:48.183+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow_clickhouse_plugin/operators/clickhouse.py", line 83, in execute
    return self._hook_execute()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow_clickhouse_plugin/operators/clickhouse.py", line 69, in _hook_execute
    return hook.execute(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow_clickhouse_plugin/hooks/clickhouse.py", line 80, in execute
    last_result = conn.execute(
  File "/home/airflow/.local/lib/python3.9/site-packages/clickhouse_driver/client.py", line 370, in execute
    with self.disconnect_on_error(query, settings):
  File "/usr/local/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/home/airflow/.local/lib/python3.9/site-packages/clickhouse_driver/client.py", line 313, in disconnect_on_error
    self.establish_connection(settings)
  File "/home/airflow/.local/lib/python3.9/site-packages/clickhouse_driver/client.py", line 300, in establish_connection
    self.connection.force_connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/clickhouse_driver/connection.py", line 258, in force_connect
    self.connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/clickhouse_driver/connection.py", line 399, in connect
    return self._init_connection(host, port)
  File "/home/airflow/.local/lib/python3.9/site-packages/clickhouse_driver/connection.py", line 343, in _init_connection
    self.receive_hello()
  File "/home/airflow/.local/lib/python3.9/site-packages/clickhouse_driver/connection.py", line 534, in receive_hello
    raise errors.UnexpectedPacketFromServerError(message)
clickhouse_driver.errors.UnexpectedPacketFromServerError: Code: 102. Unexpected packet from server clickhouse:8123 (expected Hello or Exception, got Unknown packet)
[2025-03-11T09:19:48.189+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=clickhouse_operator_example, task_id=create_table, execution_date=20240101T000000, start_date=20250311T091947, end_date=20250311T091948
[2025-03-11T09:19:48.200+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 50 for task create_table (Code: 102. Unexpected packet from server clickhouse:8123 (expected Hello or Exception, got Unknown packet); 481)
[2025-03-11T09:19:48.219+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-03-11T09:19:48.235+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-11T09:22:27.290+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: clickhouse_operator_example.create_table scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-03-11T09:22:27.296+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: clickhouse_operator_example.create_table scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-03-11T09:22:27.296+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-03-11T09:22:27.310+0000] {taskinstance.py:2191} INFO - Executing <Task(ClickHouseOperator): create_table> on 2024-01-01 00:00:00+00:00
[2025-03-11T09:22:27.315+0000] {standard_task_runner.py:60} INFO - Started process 607 to run task
[2025-03-11T09:22:27.318+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'clickhouse_operator_example', 'create_table', 'scheduled__2024-01-01T00:00:00+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/5_2_operator.py', '--cfg-path', '/tmp/tmp9wmzs49_']
[2025-03-11T09:22:27.320+0000] {standard_task_runner.py:88} INFO - Job 50: Subtask create_table
[2025-03-11T09:22:27.354+0000] {task_command.py:423} INFO - Running <TaskInstance: clickhouse_operator_example.create_table scheduled__2024-01-01T00:00:00+00:00 [running]> on host 9a2e4036dec3
[2025-03-11T09:22:27.569+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='clickhouse_operator_example' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T00:00:00+00:00'
[2025-03-11T09:22:27.577+0000] {base.py:83} INFO - Using connection ID 'clickhouse_default' for task execution.
[2025-03-11T09:22:27.578+0000] {clickhouse.py:79} INFO - CREATE TABLE IF NOT EXISTS currency_sql (date String, currency_source String, currency String, value Float) ENGINE Log
[2025-03-11T09:22:27.581+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow_clickhouse_plugin/operators/clickhouse.py", line 83, in execute
    return self._hook_execute()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow_clickhouse_plugin/operators/clickhouse.py", line 69, in _hook_execute
    return hook.execute(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow_clickhouse_plugin/hooks/clickhouse.py", line 80, in execute
    last_result = conn.execute(
  File "/home/airflow/.local/lib/python3.9/site-packages/clickhouse_driver/client.py", line 370, in execute
    with self.disconnect_on_error(query, settings):
  File "/usr/local/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/home/airflow/.local/lib/python3.9/site-packages/clickhouse_driver/client.py", line 313, in disconnect_on_error
    self.establish_connection(settings)
  File "/home/airflow/.local/lib/python3.9/site-packages/clickhouse_driver/client.py", line 300, in establish_connection
    self.connection.force_connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/clickhouse_driver/connection.py", line 258, in force_connect
    self.connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/clickhouse_driver/connection.py", line 399, in connect
    return self._init_connection(host, port)
  File "/home/airflow/.local/lib/python3.9/site-packages/clickhouse_driver/connection.py", line 343, in _init_connection
    self.receive_hello()
  File "/home/airflow/.local/lib/python3.9/site-packages/clickhouse_driver/connection.py", line 534, in receive_hello
    raise errors.UnexpectedPacketFromServerError(message)
clickhouse_driver.errors.UnexpectedPacketFromServerError: Code: 102. Unexpected packet from server clickhouse:8123 (expected Hello or Exception, got Unknown packet)
[2025-03-11T09:22:27.587+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=clickhouse_operator_example, task_id=create_table, execution_date=20240101T000000, start_date=20250311T092227, end_date=20250311T092227
[2025-03-11T09:22:27.597+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 50 for task create_table (Code: 102. Unexpected packet from server clickhouse:8123 (expected Hello or Exception, got Unknown packet); 607)
[2025-03-11T09:22:27.612+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-03-11T09:22:27.626+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-11T09:24:28.147+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: clickhouse_operator_example.create_table scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-03-11T09:24:28.152+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: clickhouse_operator_example.create_table scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-03-11T09:24:28.152+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-03-11T09:24:28.162+0000] {taskinstance.py:2191} INFO - Executing <Task(ClickHouseOperator): create_table> on 2024-01-01 00:00:00+00:00
[2025-03-11T09:24:28.166+0000] {standard_task_runner.py:60} INFO - Started process 718 to run task
[2025-03-11T09:24:28.168+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'clickhouse_operator_example', 'create_table', 'scheduled__2024-01-01T00:00:00+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/5_2_operator.py', '--cfg-path', '/tmp/tmp_8dfg3ap']
[2025-03-11T09:24:28.170+0000] {standard_task_runner.py:88} INFO - Job 50: Subtask create_table
[2025-03-11T09:24:28.196+0000] {task_command.py:423} INFO - Running <TaskInstance: clickhouse_operator_example.create_table scheduled__2024-01-01T00:00:00+00:00 [running]> on host 9a2e4036dec3
[2025-03-11T09:24:28.352+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='clickhouse_operator_example' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T00:00:00+00:00'
[2025-03-11T09:24:28.356+0000] {base.py:83} INFO - Using connection ID 'clickhouse_default' for task execution.
[2025-03-11T09:24:28.357+0000] {clickhouse.py:79} INFO - CREATE TABLE IF NOT EXISTS currency_sql (date String, currency_source String, currency String, value Float) ENGINE Log
[2025-03-11T09:24:28.359+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow_clickhouse_plugin/operators/clickhouse.py", line 83, in execute
    return self._hook_execute()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow_clickhouse_plugin/operators/clickhouse.py", line 69, in _hook_execute
    return hook.execute(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow_clickhouse_plugin/hooks/clickhouse.py", line 80, in execute
    last_result = conn.execute(
  File "/home/airflow/.local/lib/python3.9/site-packages/clickhouse_driver/client.py", line 370, in execute
    with self.disconnect_on_error(query, settings):
  File "/usr/local/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/home/airflow/.local/lib/python3.9/site-packages/clickhouse_driver/client.py", line 313, in disconnect_on_error
    self.establish_connection(settings)
  File "/home/airflow/.local/lib/python3.9/site-packages/clickhouse_driver/client.py", line 300, in establish_connection
    self.connection.force_connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/clickhouse_driver/connection.py", line 258, in force_connect
    self.connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/clickhouse_driver/connection.py", line 399, in connect
    return self._init_connection(host, port)
  File "/home/airflow/.local/lib/python3.9/site-packages/clickhouse_driver/connection.py", line 343, in _init_connection
    self.receive_hello()
  File "/home/airflow/.local/lib/python3.9/site-packages/clickhouse_driver/connection.py", line 534, in receive_hello
    raise errors.UnexpectedPacketFromServerError(message)
clickhouse_driver.errors.UnexpectedPacketFromServerError: Code: 102. Unexpected packet from server clickhouse:8123 (expected Hello or Exception, got Unknown packet)
[2025-03-11T09:24:28.363+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=clickhouse_operator_example, task_id=create_table, execution_date=20240101T000000, start_date=20250311T092428, end_date=20250311T092428
[2025-03-11T09:24:28.372+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 50 for task create_table (Code: 102. Unexpected packet from server clickhouse:8123 (expected Hello or Exception, got Unknown packet); 718)
[2025-03-11T09:24:28.422+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-03-11T09:24:28.434+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-11T09:28:03.945+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: clickhouse_operator_example.create_table scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-03-11T09:28:03.954+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: clickhouse_operator_example.create_table scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-03-11T09:28:03.954+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-03-11T09:28:03.969+0000] {taskinstance.py:2191} INFO - Executing <Task(ClickHouseOperator): create_table> on 2024-01-01 00:00:00+00:00
[2025-03-11T09:28:03.974+0000] {standard_task_runner.py:60} INFO - Started process 860 to run task
[2025-03-11T09:28:03.977+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'clickhouse_operator_example', 'create_table', 'scheduled__2024-01-01T00:00:00+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/5_2_operator.py', '--cfg-path', '/tmp/tmptm21fmwe']
[2025-03-11T09:28:03.979+0000] {standard_task_runner.py:88} INFO - Job 50: Subtask create_table
[2025-03-11T09:28:04.011+0000] {task_command.py:423} INFO - Running <TaskInstance: clickhouse_operator_example.create_table scheduled__2024-01-01T00:00:00+00:00 [running]> on host 9a2e4036dec3
[2025-03-11T09:28:04.193+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='clickhouse_operator_example' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T00:00:00+00:00'
[2025-03-11T09:28:04.200+0000] {base.py:83} INFO - Using connection ID 'clickhouse_default' for task execution.
[2025-03-11T09:28:04.201+0000] {clickhouse.py:79} INFO - CREATE TABLE IF NOT EXISTS currency_sql (date String, currency_source String, currency String, value Float) ENGINE Log
[2025-03-11T09:28:08.238+0000] {connection.py:411} WARNING - Failed to connect to airflow_network:8123
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/clickhouse_driver/connection.py", line 399, in connect
    return self._init_connection(host, port)
  File "/home/airflow/.local/lib/python3.9/site-packages/clickhouse_driver/connection.py", line 329, in _init_connection
    self.socket = self._create_socket(host, port)
  File "/home/airflow/.local/lib/python3.9/site-packages/clickhouse_driver/connection.py", line 280, in _create_socket
    for res in socket.getaddrinfo(host, port, 0, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
[2025-03-11T09:28:08.241+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow_clickhouse_plugin/operators/clickhouse.py", line 83, in execute
    return self._hook_execute()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow_clickhouse_plugin/operators/clickhouse.py", line 69, in _hook_execute
    return hook.execute(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow_clickhouse_plugin/hooks/clickhouse.py", line 80, in execute
    last_result = conn.execute(
  File "/home/airflow/.local/lib/python3.9/site-packages/clickhouse_driver/client.py", line 370, in execute
    with self.disconnect_on_error(query, settings):
  File "/usr/local/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/home/airflow/.local/lib/python3.9/site-packages/clickhouse_driver/client.py", line 313, in disconnect_on_error
    self.establish_connection(settings)
  File "/home/airflow/.local/lib/python3.9/site-packages/clickhouse_driver/client.py", line 300, in establish_connection
    self.connection.force_connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/clickhouse_driver/connection.py", line 258, in force_connect
    self.connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/clickhouse_driver/connection.py", line 420, in connect
    raise err
clickhouse_driver.errors.NetworkError: Code: 210. Name or service not known (airflow_network:8123)
[2025-03-11T09:28:08.245+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=clickhouse_operator_example, task_id=create_table, execution_date=20240101T000000, start_date=20250311T092803, end_date=20250311T092808
[2025-03-11T09:28:08.259+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 50 for task create_table (Code: 210. Name or service not known (airflow_network:8123); 860)
[2025-03-11T09:28:08.282+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-03-11T09:28:08.296+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-11T09:29:51.914+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: clickhouse_operator_example.create_table scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-03-11T09:29:51.925+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: clickhouse_operator_example.create_table scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-03-11T09:29:51.926+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-03-11T09:29:51.951+0000] {taskinstance.py:2191} INFO - Executing <Task(ClickHouseOperator): create_table> on 2024-01-01 00:00:00+00:00
[2025-03-11T09:29:51.958+0000] {standard_task_runner.py:60} INFO - Started process 964 to run task
[2025-03-11T09:29:51.962+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'clickhouse_operator_example', 'create_table', 'scheduled__2024-01-01T00:00:00+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/5_2_operator.py', '--cfg-path', '/tmp/tmp8z8ji0o3']
[2025-03-11T09:29:51.964+0000] {standard_task_runner.py:88} INFO - Job 50: Subtask create_table
[2025-03-11T09:29:52.099+0000] {task_command.py:423} INFO - Running <TaskInstance: clickhouse_operator_example.create_table scheduled__2024-01-01T00:00:00+00:00 [running]> on host 9a2e4036dec3
[2025-03-11T09:29:52.440+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='clickhouse_operator_example' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T00:00:00+00:00'
[2025-03-11T09:29:52.447+0000] {base.py:83} INFO - Using connection ID 'clickhouse_def' for task execution.
[2025-03-11T09:29:52.448+0000] {clickhouse.py:79} INFO - CREATE TABLE IF NOT EXISTS currency_sql (date String, currency_source String, currency String, value Float) ENGINE Log
[2025-03-11T09:29:52.472+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow_clickhouse_plugin/operators/clickhouse.py", line 83, in execute
    return self._hook_execute()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow_clickhouse_plugin/operators/clickhouse.py", line 69, in _hook_execute
    return hook.execute(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow_clickhouse_plugin/hooks/clickhouse.py", line 80, in execute
    last_result = conn.execute(
  File "/home/airflow/.local/lib/python3.9/site-packages/clickhouse_driver/client.py", line 370, in execute
    with self.disconnect_on_error(query, settings):
  File "/usr/local/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/home/airflow/.local/lib/python3.9/site-packages/clickhouse_driver/client.py", line 313, in disconnect_on_error
    self.establish_connection(settings)
  File "/home/airflow/.local/lib/python3.9/site-packages/clickhouse_driver/client.py", line 300, in establish_connection
    self.connection.force_connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/clickhouse_driver/connection.py", line 258, in force_connect
    self.connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/clickhouse_driver/connection.py", line 399, in connect
    return self._init_connection(host, port)
  File "/home/airflow/.local/lib/python3.9/site-packages/clickhouse_driver/connection.py", line 343, in _init_connection
    self.receive_hello()
  File "/home/airflow/.local/lib/python3.9/site-packages/clickhouse_driver/connection.py", line 534, in receive_hello
    raise errors.UnexpectedPacketFromServerError(message)
clickhouse_driver.errors.UnexpectedPacketFromServerError: Code: 102. Unexpected packet from server clickhouse:8123 (expected Hello or Exception, got Unknown packet)
[2025-03-11T09:29:52.492+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=clickhouse_operator_example, task_id=create_table, execution_date=20240101T000000, start_date=20250311T092951, end_date=20250311T092952
[2025-03-11T09:29:52.514+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 50 for task create_table (Code: 102. Unexpected packet from server clickhouse:8123 (expected Hello or Exception, got Unknown packet); 964)
[2025-03-11T09:29:52.537+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-03-11T09:29:52.559+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-11T09:52:49.025+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: clickhouse_operator_example.create_table scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-03-11T09:52:49.031+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: clickhouse_operator_example.create_table scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-03-11T09:52:49.031+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-03-11T09:52:49.045+0000] {taskinstance.py:2191} INFO - Executing <Task(ClickHouseOperator): create_table> on 2024-01-01 00:00:00+00:00
[2025-03-11T09:52:49.050+0000] {standard_task_runner.py:60} INFO - Started process 1519 to run task
[2025-03-11T09:52:49.053+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'clickhouse_operator_example', 'create_table', 'scheduled__2024-01-01T00:00:00+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/5_2_operator.py', '--cfg-path', '/tmp/tmphv3bnwzl']
[2025-03-11T09:52:49.055+0000] {standard_task_runner.py:88} INFO - Job 50: Subtask create_table
[2025-03-11T09:52:49.089+0000] {task_command.py:423} INFO - Running <TaskInstance: clickhouse_operator_example.create_table scheduled__2024-01-01T00:00:00+00:00 [running]> on host 9a2e4036dec3
[2025-03-11T09:52:49.283+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='clickhouse_operator_example' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T00:00:00+00:00'
[2025-03-11T09:52:49.291+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow_clickhouse_plugin/operators/clickhouse.py", line 83, in execute
    return self._hook_execute()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow_clickhouse_plugin/operators/clickhouse.py", line 69, in _hook_execute
    return hook.execute(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow_clickhouse_plugin/hooks/clickhouse.py", line 76, in execute
    with _disconnecting(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow_clickhouse_plugin/hooks/clickhouse.py", line 53, in get_conn
    conn = self.get_connection(self._clickhouse_conn_id)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/hooks/base.py", line 82, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/connection.py", line 479, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `clickhouse_def` isn't defined
[2025-03-11T09:52:49.295+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=clickhouse_operator_example, task_id=create_table, execution_date=20240101T000000, start_date=20250311T095249, end_date=20250311T095249
[2025-03-11T09:52:49.305+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 50 for task create_table (The conn_id `clickhouse_def` isn't defined; 1519)
[2025-03-11T09:52:49.346+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-03-11T09:52:49.361+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-11T09:53:59.245+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: clickhouse_operator_example.create_table scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-03-11T09:53:59.254+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: clickhouse_operator_example.create_table scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-03-11T09:53:59.254+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-03-11T09:53:59.270+0000] {taskinstance.py:2191} INFO - Executing <Task(ClickHouseOperator): create_table> on 2024-01-01 00:00:00+00:00
[2025-03-11T09:53:59.277+0000] {standard_task_runner.py:60} INFO - Started process 1610 to run task
[2025-03-11T09:53:59.280+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'clickhouse_operator_example', 'create_table', 'scheduled__2024-01-01T00:00:00+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/5_2_operator.py', '--cfg-path', '/tmp/tmpwe7hpy2p']
[2025-03-11T09:53:59.283+0000] {standard_task_runner.py:88} INFO - Job 50: Subtask create_table
[2025-03-11T09:53:59.325+0000] {task_command.py:423} INFO - Running <TaskInstance: clickhouse_operator_example.create_table scheduled__2024-01-01T00:00:00+00:00 [running]> on host 9a2e4036dec3
[2025-03-11T09:53:59.518+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='clickhouse_operator_example' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T00:00:00+00:00'
[2025-03-11T09:53:59.525+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow_clickhouse_plugin/operators/clickhouse.py", line 83, in execute
    return self._hook_execute()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow_clickhouse_plugin/operators/clickhouse.py", line 69, in _hook_execute
    return hook.execute(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow_clickhouse_plugin/hooks/clickhouse.py", line 76, in execute
    with _disconnecting(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow_clickhouse_plugin/hooks/clickhouse.py", line 53, in get_conn
    conn = self.get_connection(self._clickhouse_conn_id)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/hooks/base.py", line 82, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/connection.py", line 479, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `clickhouse_def` isn't defined
[2025-03-11T09:53:59.527+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=clickhouse_operator_example, task_id=create_table, execution_date=20240101T000000, start_date=20250311T095359, end_date=20250311T095359
[2025-03-11T09:53:59.537+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 50 for task create_table (The conn_id `clickhouse_def` isn't defined; 1610)
[2025-03-11T09:53:59.575+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-03-11T09:53:59.591+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-11T09:55:08.567+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: clickhouse_operator_example.create_table scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-03-11T09:55:08.574+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: clickhouse_operator_example.create_table scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-03-11T09:55:08.574+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-03-11T09:55:08.590+0000] {taskinstance.py:2191} INFO - Executing <Task(ClickHouseOperator): create_table> on 2024-01-01 00:00:00+00:00
[2025-03-11T09:55:08.595+0000] {standard_task_runner.py:60} INFO - Started process 1704 to run task
[2025-03-11T09:55:08.598+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'clickhouse_operator_example', 'create_table', 'scheduled__2024-01-01T00:00:00+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/5_2_operator.py', '--cfg-path', '/tmp/tmpbjrtbln6']
[2025-03-11T09:55:08.600+0000] {standard_task_runner.py:88} INFO - Job 50: Subtask create_table
[2025-03-11T09:55:08.635+0000] {task_command.py:423} INFO - Running <TaskInstance: clickhouse_operator_example.create_table scheduled__2024-01-01T00:00:00+00:00 [running]> on host 9a2e4036dec3
[2025-03-11T09:55:08.805+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='clickhouse_operator_example' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T00:00:00+00:00'
[2025-03-11T09:55:08.809+0000] {base.py:83} INFO - Using connection ID 'clickhouse_default' for task execution.
[2025-03-11T09:55:08.810+0000] {clickhouse.py:79} INFO - CREATE TABLE IF NOT EXISTS currency_sql (date String, currency_source String, currency String, value Float) ENGINE Log
[2025-03-11T09:55:08.811+0000] {connection.py:411} WARNING - Failed to connect to localhost:9000
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/clickhouse_driver/connection.py", line 399, in connect
    return self._init_connection(host, port)
  File "/home/airflow/.local/lib/python3.9/site-packages/clickhouse_driver/connection.py", line 329, in _init_connection
    self.socket = self._create_socket(host, port)
  File "/home/airflow/.local/lib/python3.9/site-packages/clickhouse_driver/connection.py", line 301, in _create_socket
    raise err
  File "/home/airflow/.local/lib/python3.9/site-packages/clickhouse_driver/connection.py", line 292, in _create_socket
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
[2025-03-11T09:55:08.812+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow_clickhouse_plugin/operators/clickhouse.py", line 83, in execute
    return self._hook_execute()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow_clickhouse_plugin/operators/clickhouse.py", line 69, in _hook_execute
    return hook.execute(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow_clickhouse_plugin/hooks/clickhouse.py", line 80, in execute
    last_result = conn.execute(
  File "/home/airflow/.local/lib/python3.9/site-packages/clickhouse_driver/client.py", line 370, in execute
    with self.disconnect_on_error(query, settings):
  File "/usr/local/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/home/airflow/.local/lib/python3.9/site-packages/clickhouse_driver/client.py", line 313, in disconnect_on_error
    self.establish_connection(settings)
  File "/home/airflow/.local/lib/python3.9/site-packages/clickhouse_driver/client.py", line 300, in establish_connection
    self.connection.force_connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/clickhouse_driver/connection.py", line 258, in force_connect
    self.connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/clickhouse_driver/connection.py", line 420, in connect
    raise err
clickhouse_driver.errors.NetworkError: Code: 210. Connection refused (localhost:9000)
[2025-03-11T09:55:08.816+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=clickhouse_operator_example, task_id=create_table, execution_date=20240101T000000, start_date=20250311T095508, end_date=20250311T095508
[2025-03-11T09:55:08.825+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 50 for task create_table (Code: 210. Connection refused (localhost:9000); 1704)
[2025-03-11T09:55:08.851+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-03-11T09:55:08.864+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-11T09:56:40.693+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: clickhouse_operator_example.create_table scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-03-11T09:56:40.700+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: clickhouse_operator_example.create_table scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-03-11T09:56:40.701+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-03-11T09:56:40.719+0000] {taskinstance.py:2191} INFO - Executing <Task(ClickHouseOperator): create_table> on 2024-01-01 00:00:00+00:00
[2025-03-11T09:56:40.730+0000] {standard_task_runner.py:60} INFO - Started process 1804 to run task
[2025-03-11T09:56:40.734+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'clickhouse_operator_example', 'create_table', 'scheduled__2024-01-01T00:00:00+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/5_2_operator.py', '--cfg-path', '/tmp/tmp5kaebw0u']
[2025-03-11T09:56:40.736+0000] {standard_task_runner.py:88} INFO - Job 50: Subtask create_table
[2025-03-11T09:56:40.782+0000] {task_command.py:423} INFO - Running <TaskInstance: clickhouse_operator_example.create_table scheduled__2024-01-01T00:00:00+00:00 [running]> on host 9a2e4036dec3
[2025-03-11T09:56:40.953+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='clickhouse_operator_example' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T00:00:00+00:00'
[2025-03-11T09:56:40.957+0000] {base.py:83} INFO - Using connection ID 'clickhouse_default' for task execution.
[2025-03-11T09:56:40.958+0000] {clickhouse.py:79} INFO - CREATE TABLE IF NOT EXISTS currency_sql (date String, currency_source String, currency String, value Float) ENGINE Log
[2025-03-11T09:56:41.071+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=clickhouse_operator_example, task_id=create_table, execution_date=20240101T000000, start_date=20250311T095640, end_date=20250311T095641
[2025-03-11T09:56:41.107+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-11T09:56:41.122+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-11T10:05:06.878+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: clickhouse_operator_example.create_table scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-03-11T10:05:06.885+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: clickhouse_operator_example.create_table scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-03-11T10:05:06.885+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-03-11T10:05:06.904+0000] {taskinstance.py:2191} INFO - Executing <Task(ClickHouseOperator): create_table> on 2024-01-01 00:00:00+00:00
[2025-03-11T10:05:06.909+0000] {standard_task_runner.py:60} INFO - Started process 2119 to run task
[2025-03-11T10:05:06.912+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'clickhouse_operator_example', 'create_table', 'scheduled__2024-01-01T00:00:00+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/5_2_operator.py', '--cfg-path', '/tmp/tmphfboh49u']
[2025-03-11T10:05:06.914+0000] {standard_task_runner.py:88} INFO - Job 50: Subtask create_table
[2025-03-11T10:05:06.956+0000] {task_command.py:423} INFO - Running <TaskInstance: clickhouse_operator_example.create_table scheduled__2024-01-01T00:00:00+00:00 [running]> on host 9a2e4036dec3
[2025-03-11T10:05:07.124+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='clickhouse_operator_example' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T00:00:00+00:00'
[2025-03-11T10:05:07.127+0000] {base.py:83} INFO - Using connection ID 'clickhouse_default' for task execution.
[2025-03-11T10:05:07.128+0000] {clickhouse.py:79} INFO - CREATE TABLE IF NOT EXISTS currency_sql (date String, currency_source String, currency String, value Float) ENGINE Log
[2025-03-11T10:05:07.162+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=clickhouse_operator_example, task_id=create_table, execution_date=20240101T000000, start_date=20250311T100506, end_date=20250311T100507
[2025-03-11T10:05:07.205+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-11T10:05:07.220+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
