[2025-03-12T14:40:48.523+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 5_2_2_house_assignment.transform_data scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2025-03-12T14:40:48.528+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 5_2_2_house_assignment.transform_data scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2025-03-12T14:40:48.529+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-03-12T14:40:48.542+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): transform_data> on 2024-01-05 00:00:00+00:00
[2025-03-12T14:40:48.549+0000] {standard_task_runner.py:60} INFO - Started process 1835 to run task
[2025-03-12T14:40:48.551+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', '5_2_2_house_assignment', 'transform_data', 'scheduled__2024-01-05T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/5_2_2_house_assignment.py', '--cfg-path', '/tmp/tmpha9jn1_c']
[2025-03-12T14:40:48.554+0000] {standard_task_runner.py:88} INFO - Job 14: Subtask transform_data
[2025-03-12T14:40:48.591+0000] {task_command.py:423} INFO - Running <TaskInstance: 5_2_2_house_assignment.transform_data scheduled__2024-01-05T00:00:00+00:00 [running]> on host 13d00b3af9e0
[2025-03-12T14:40:48.648+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='5_2_2_house_assignment' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2024-01-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-05T00:00:00+00:00'
[2025-03-12T14:40:48.650+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/5_2_2_house_assignment.py", line 50, in transform_data
    tree = ET.parse(s_file, parser=parser).getroot()
  File "/usr/local/lib/python3.9/xml/etree/ElementTree.py", line 1222, in parse
    tree.parse(source, parser)
  File "/usr/local/lib/python3.9/xml/etree/ElementTree.py", line 586, in parse
    parser.feed(data)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0
[2025-03-12T14:40:48.655+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=5_2_2_house_assignment, task_id=transform_data, execution_date=20240105T000000, start_date=20250312T144048, end_date=20250312T144048
[2025-03-12T14:40:48.659+0000] {base.py:83} INFO - Using connection ID 'telegram_id' for task execution.
[2025-03-12T14:40:48.661+0000] {base.py:83} INFO - Using connection ID 'telegram_id' for task execution.
[2025-03-12T14:40:49.381+0000] {_client.py:1740} INFO - HTTP Request: POST https://api.telegram.org/bot7637994734:AAGvM2WRHeVQYm8VJwtx1lyk6bN6LERhzT0/sendMessage "HTTP/1.1 200 OK"
[2025-03-12T14:40:49.397+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 14 for task transform_data (not well-formed (invalid token): line 1, column 0; 1835)
[2025-03-12T14:40:49.447+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-03-12T14:54:29.937+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 5_2_2_house_assignment.transform_data scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2025-03-12T14:54:29.942+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 5_2_2_house_assignment.transform_data scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2025-03-12T14:54:29.942+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-03-12T14:54:29.952+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): transform_data> on 2024-01-05 00:00:00+00:00
[2025-03-12T14:54:29.957+0000] {standard_task_runner.py:60} INFO - Started process 3149 to run task
[2025-03-12T14:54:29.960+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', '5_2_2_house_assignment', 'transform_data', 'scheduled__2024-01-05T00:00:00+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/5_2_2_house_assignment.py', '--cfg-path', '/tmp/tmp253ut0uu']
[2025-03-12T14:54:29.961+0000] {standard_task_runner.py:88} INFO - Job 22: Subtask transform_data
[2025-03-12T14:54:29.989+0000] {task_command.py:423} INFO - Running <TaskInstance: 5_2_2_house_assignment.transform_data scheduled__2024-01-05T00:00:00+00:00 [running]> on host 13d00b3af9e0
[2025-03-12T14:54:30.048+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='5_2_2_house_assignment' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2024-01-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-05T00:00:00+00:00'
[2025-03-12T14:54:30.064+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-03-12T14:54:30.070+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=5_2_2_house_assignment, task_id=transform_data, execution_date=20240105T000000, start_date=20250312T145429, end_date=20250312T145430
[2025-03-12T14:54:30.092+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
